-- Manual migration: positions cache refactor + quarterly earnings table
-- Date: 2026-04-19
-- Target DB: PostgreSQL
--
-- Purpose:
-- 1) Introduce earnings_history as the source table for quarterly EPS.
-- 2) Keep positions as a lightweight market-data cache.
-- 3) Remove redundant columns now derived from transactions.

BEGIN;

-- 1) Create quarterly earnings table if it does not exist.
CREATE TABLE IF NOT EXISTS public.earnings_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    as_of_date DATE NOT NULL,
    basic_eps NUMERIC(19,4) NOT NULL,
    captured_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_earnings_history_symbol_asof UNIQUE (symbol, as_of_date)
);

-- 2) Drop legacy unique constraint name created by Hibernate (if present),
--    then ensure a stable explicit unique constraint exists.
ALTER TABLE public.earnings_history
    DROP CONSTRAINT IF EXISTS ukmf17pkf1u2e5fitaegxe3lubx;

ALTER TABLE public.earnings_history
    DROP CONSTRAINT IF EXISTS uk_earnings_history_symbol_asof;

ALTER TABLE public.earnings_history
    ADD CONSTRAINT uk_earnings_history_symbol_asof UNIQUE (symbol, as_of_date);

-- 3) Refactor positions to cache-only columns.
ALTER TABLE public.positions
    DROP COLUMN IF EXISTS average_cost,
    DROP COLUMN IF EXISTS quantity,
    DROP COLUMN IF EXISTS latest_peg,
    DROP COLUMN IF EXISTS pe_updated_at;

COMMIT;
