-- Manual migration: overview user/AI note panel
-- Date: 2026-05-03

BEGIN;

CREATE TABLE IF NOT EXISTS public.overview_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_type VARCHAR(20) NOT NULL,
    note TEXT NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_overview_notes_type UNIQUE (note_type)
);

COMMIT;
