CREATE TABLE IF NOT EXISTS valuation_notes (
    id BIGSERIAL PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    symbol VARCHAR(20) NOT NULL UNIQUE,
    note TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
