-- Manual migration: symbol-level notes for one-time fundamental/accounting items
-- Date: 2026-05-16
-- Target DB: PostgreSQL

BEGIN;

CREATE TABLE IF NOT EXISTS public.fundamental_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_fundamental_notes_symbol UNIQUE (symbol)
);

COMMIT;
